import StyledComponentsRegistry from "@/components/shared/StyledComopnentRegistry";
import "./globals.css";
import { Inter } from "next/font/google";
import GoogleAnalytics from "@/components/shared/GoogleAnalytics";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "in-cars",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="logo.svg" type="image/x-icon" />
      </head>
      <body className={inter.className}>
        <GoogleAnalytics />
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
